name: auto-test
on: [push]
jobs:
  make-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: permission
        run: chmod +x ./test.sh

      - name: make test
        run: make test